- name: Overview
  href: index.md
- name: Core Services
  items:
    - name: Backend
      uid: NetworkMonitoring.Backend
    - name: Probe
      uid: NetworkMonitoring.Probe
    - name: Integration Console
      uid: NetworkMonitoring.IntegrationConsole
- name: Domain Model
  items:
    - name: Domain Shared
      uid: NetworkMonitoring.Domain
- name: Testing Suite
  items:
    - name: Backend Integration Tests
      uid: NetworkMonitoring.Backend.IntegrationTests
    - name: Backend Unit Tests
      uid: NetworkMonitoring.Backend.UnitTests
    - name: Probe Integration Tests
      uid: NetworkMonitoring.Probe.IntegrationTests
    - name: Probe Unit Tests
      uid: NetworkMonitoring.Probe.UnitTests
    - name: Integration Console Integration Tests
      uid: NetworkMonitoring.IntegrationConsole.IntegrationTests
    - name: Integration Console Unit Tests
      uid: NetworkMonitoring.IntegrationConsole.UnitTests
